using UnityEngine;

class Orb : RangedWeapon
{
    /* 
        Inherited attributes:
          Sprite itemSprite  - Sprite of the weapon in the inventory
          Sprite itemName    - String used for item in inventory

          float swingTimer   - Time between attacks / Attack speed
          int damage         - Base damage the weapon does
          float knockback      - The amound of knockback the weapon does
          GameObject attack  - Prefab GameObject generated by the weapon

          int maxAmmo        - Number of shots that can loaded at once
          int minAmmo        - Number of ammo need to even shoot
          int curAmmo        - Number of ammo that the weapon currently has
          int reloadAmmo     - Number of ammo reloaded every timer
          float reloadTime   - Amount of time it takes to reload one reloadAmmo
          float speed        - Speed of the projectile
    */

    public Orb(Transform hero) : base(hero)
    {
        // Orb swing timer: long
        swingTime = 0.7f;
        // Orb base damage: low
        damage = 1;
        // Orb knockback
        knockback = 5f;
        // Load up the attack object
        attack = Resources.Load("Prefabs/OrbAttack") as GameObject;
        // Orb sprite
        //sprite = Resources.Load("Sprites/Orb") as Sprite;

        maxAmmo = 4; // + stats.BonusMaxAmmo
        minAmmo = 1;
        curAmmo = maxAmmo; // Start with full ammo

        reloadAmmo = 1;
        reloadTime = 0.25f;

        speed = 10.0f;
    }
}
