using UnityEngine;

class Lance : MeleeWeapon
{
    /* 
        Inherited attributes:
          Sprite itemSprite    - Sprite of the weapon in the inventory
          string itemName      - Name of the item

          float swingTimer     - Time between attacks / Attack speed
          int damage           - Base damage the weapon does
          float knockback      - The amound of knockback the weapon does
          GameObject attack    - Prefab GameObject generated by the weapon
          
          Vector2 attackOffset - Vector to offset the position by (so it doesn't collide with the hero)
    */

    public Lance(Transform hero) : base(hero)
    {
        itemName = "Lance";

        // Lance swing timer: short
        swingTime = 0.4f;

        // Lance base damage: 1
        damage = 1;

        // Lance knockback
        knockback = 5f;

        // Load up the attack 
        attack = Resources.Load("Prefabs/LanceAttack") as GameObject;

        // Lance sprite
        //sprite = Resources.Load("Sprites/Sword") as Sprite;
        itemName = "Lance";

        attackOffset = new Vector2(1.28f, 0);
    }
}
