using UnityEngine;

class Gun : RangedWeapon
{
    /* 
        Inherited attributes:
          float swingTimer   - Time between attacks / Attack speed
          int damage         - Base damage the weapon does
          GameObject attack  - Prefab GameObject generated by the weapon
          Sprite sprite      - Sprite of the weapon in the inventory

          int maxAmmo        - Number of shots that can loaded at once
          int minAmmo        - Number of ammo need to even shoot
          int curAmmo        - Number of ammo that the weapon currently has

          int reloadAmmo     - Number of ammo reloaded every timer
          float reloadTimer  - Amount of time it takes to reload one reloadAmmo

          float speed        - Speed of the projectile
    */

    public Gun(Transform hero) : base(hero)
    {
        // Gun swing timer: short
        swingTime = 0.1f;
        // Gun base damage: low
        damage = 1;
        // Load up the attack object
        attack = Resources.Load("Prefabs/Bullet") as GameObject;
        // Gun sprite
        //sprite = Resources.Load("Sprites/Gun") as Sprite;

        maxAmmo = 6; // + stats.BonusMaxAmmo
        minAmmo = 1;
        curAmmo = 6; // Start with full ammo

        reloadAmmo = 1;
        reloadTimer = 0.5f;

        speed = 15.0f;
    }
}
