using UnityEngine;

class Sword : MeleeWeapon
{
    /* 
        Inherited attributes:
          float swingTimer   - Time between attacks / Attack speed
          int damage         - Base damage the weapon does
          GameObject attack  - Prefab GameObject generated by the weapon
          Sprite sprite      - Sprite of the weapon in the inventory
    */

    public Sword(Transform hero) : base(hero)
    {
        // Sword swing timer: short
        swingTime = 0.5f;

        // Sword base damage: 1
        damage = 1;

        // Load up the attack 
        attack = Resources.Load("Prefabs/PlayerSlash") as GameObject;

        // Sword sprit
        //sprite = Resources.Load("Sprites/Sword") as Sprite;
    }
}
